apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sam
resources:
  - service-account.yaml
  - role.yaml
  - rolebinding.yaml
  - istio-service.yaml
  - deployment.yaml
  - service.yaml
