name: Broadbot auto-approve
on: pull_request

permissions:
  pull-requests: write

jobs:
  getActor:
    runs-on: ubuntu-latest
    steps:
    - name: "Echo github actor"
      env:
        GH_ACTOR: ${{ github.actor }}
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      run: echo "$GH_ACTOR" && echo "$PR_AUTHOR"
  broadbot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'broadbot'
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
