name: Sam PR tests

on:
  pull_request:
    branches:
      - QA-2001
    paths-ignore:
      - 'README.md'

env:
  GOOGLE_PROJECT: dsp-artifact-registry
  # Name of the app-specific Docker repository configured in GOOGLE_PROJECT
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  # Name of the image to make in REPOSITORY_NAME
  JAR_IMAGE_NAME: jar
  # Region-specific Google Docker repository where GOOGLE_PROJECT/REPOSITORY_NAME can be found
  GOOGLE_DOCKER_REPOSITORY: us-central1-docker.pkg.dev
  GCR_REGISTRY: io/broad-dsp-gcr-public/sam
  DOCKERHUB_REGISTRY: broadinstitute/sam
  VAULT_TOKEN: sss
jobs:
  sam-pr-test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Git config
      - name: Checkout current code
        uses: actions/checkout@v3

      # Build jar
      - name: Build Sam jar
        run: |
          ./docker/build_jar.sh

      # Publish jar
      - name: Publish Sam jar
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD) # current branch
          REGEX_TO_REPLACE_ILLEGAL_CHARACTERS_WITH_DASHES="s/[^a-zA-Z0-9_.\-]/-/g"
          REGEX_TO_REMOVE_DASHES_AND_PERIODS_FROM_BEGINNING="s/^[.\-]*//g"
          DOCKERTAG_SAFE_NAME=$(echo $BRANCH | sed -e $REGEX_TO_REPLACE_ILLEGAL_CHARACTERS_WITH_DASHES -e $REGEX_TO_REMOVE_DASHES_AND_PERIODS_FROM_BEGINNING | cut -c 1-127)  # https://docs.docker.com/engine/reference/commandline/tag/#:~:text=A%20tag%20name%20must%20be,a%20maximum%20of%20128%20characters.
          GIT_SHA=$(git rev-parse origin/${BRANCH})
          echo $GIT_SHA
          HASH_TAG=${GIT_SHA:0:12}
          echo $HASH_TAG
          SVCACCT_FILE="dspci-wb-gcr-service-account.json"
          GCR_SVCACCT_VAULT="secret/dsde/dsp-techops/common/$SVCACCT_FILE"
          VAULT_TOKEN=${{ env.VAULT_TOKEN )}

          docker run --rm  -e VAULT_TOKEN=$VAULT_TOKEN \
             broadinstitute/dsde-toolbox:latest vault read --format=json ${GCR_SVCACCT_VAULT} \
             | jq .data > ${SVCACCT_FILE}

          docker build -t ${{ env.DOCKERHUB_REGISTRY }}:${HASH_TAG} --pull .
          docker push ${{ env.DOCKERHUB_REGISTRY }}:${HASH_TAG}
          docker tag ${{ env.DOCKERHUB_REGISTRY }}:${HASH_TAG} ${{ env.DOCKERHUB_REGISTRY }}:${DOCKERTAG_SAFE_NAME}
          docker push ${{ env.DOCKERHUB_REGISTRY }}:${DOCKERTAG_SAFE_NAME}
          docker tag ${{ env.DOCKERHUB_REGISTRY }}:${HASH_TAG} ${{ env.GCR_REGISTRY }}:${HASH_TAG}
          gcloud docker -- push ${{ env.GCR_REGISTRY }}:${HASH_TAG}
