name: Sam PR tests

on:
  push:
    branches:
      - QA-2001
    paths-ignore:
      - 'README.md'
jobs:
  sam-build-tag-publish-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    outputs:
      custom-version-json: ${{ steps.render-data.outputs.custom-version-json }}
    steps:
      - name: dispatch to terra-github-workflows
        uses: aurelien-baudet/workflow-dispatch@93e95b157d791ae7f42aef8f8a0d3d723eba1c31 #commit sha for v2.1.1
        with:
          workflow: sam-build
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN}} # github token for access to kick off a job in the private repo
          # manually recalculate b/c env context is broken https://github.com/actions/runner/issues/480
          inputs: '{ "repository": "${{ github.event.repository.full_name }}", "ref": "${{ github.event.ref }}" }'

      - name: Render data to share with dependent jobs
        id: render-data
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          GIT_SHA=${{ github.sha }}
          HASH_TAG=${GIT_SHA:0:12}
          # Need to escape twice because custom-version-json is passed like an cli argument string
          echo "HASH_TAG=$HASH_TAG"
          echo ::set-output name=custom-version-json::"{\\\"jobmanager\\\":{\\\"enabled\\\":false,\\\"sam\\\":{\\\"appVersion\\\":\\\"$HASH_TAG\\\"}}"

  create-bee-workflow:
    runs-on: ubuntu-latest
    needs: [sam-build-tag-publish-job]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Check hash tag
        run: |
          echo '${{ needs.sam-build-tag-publish-job.outputs.custom-version-json }}'

      - name: dispatch to terra-github-workflows
        uses: aurelien-baudet/workflow-dispatch@93e95b157d791ae7f42aef8f8a0d3d723eba1c31 #commit sha for v2.1.1
        with:
          workflow: bee-create
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN}} # github token for access to kick off a job in the private repo
          # manually recalculate b/c env context is broken https://github.com/actions/runner/issues/480
          inputs: '{ "bee-name": "oauth-proxy-${{ github.run_id }}", "version-template": "dev", "custom-version-json": "${{ needs.sam-build-tag-publish-job.outputs.custom-version-json }}" }'

  destroy-bee-workflow:
    runs-on: ubuntu-latest
    needs: [create-bee-workflow]
    if: always() # always run to confirm bee is destroyed
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: dispatch to terra-github-workflows
        uses: aurelien-baudet/workflow-dispatch@93e95b157d791ae7f42aef8f8a0d3d723eba1c31 #commit sha for v2.1.1
        with:
          workflow: bee-destroy
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN}} # github token for access to kick off a job in the private repo
          # manually recalculate b/c env context is broken https://github.com/actions/runner/issues/480
          inputs: '{ "bee-name": "oauth-proxy-${{ github.run_id }}" }'
