# Github action to Build Sam artifact, add/promote semantic tagging and then run tests

name: sam-id-427-test

on:
  push:
    branches:
      - 'iv-test-id-427'
    paths-ignore: ['**.md']

jobs:
  destroy-bee-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: dispatch to terra-github-workflows
        uses: aurelien-baudet/workflow-dispatch@93e95b157d791ae7f42aef8f8a0d3d723eba1c31 #commit sha for v2.1.1
        with:
          workflow: bee-destroy
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN}} # github token for access to kick off a job in the private repo
          # manually recalculate b/c env context is broken https://github.com/actions/runner/issues/480
          inputs: '{ "bee-name": "sam-4243937047-dev" }'
