name: sam-smoke-tests

on:
  workflow_call:
    inputs:
      sam-hostname:
        description: 'a generic hostname for Sam'
        required: true
        type: string
      ENV:
        description: 'test environment (qa, alpha)'
        required: true
        type: string
      auth-service-account-email:
        description: 'email of auth service account to run smoke test'
        required: true
        type: string

jobs:
  sam-smoke-test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: dispatch to terra-github-workflows
        uses: aurelien-baudet/workflow-dispatch@93e95b157d791ae7f42aef8f8a0d3d723eba1c31 #commit sha for v2.1.1
        with:
          workflow: sam-smoke-tests
          repo: broadinstitute/terra-github-workflows
          ref: refs/heads/main
          token: ${{ secrets.BROADBOT_TOKEN}} # github token for access to kick off a job in the private repo
          # manually recalculate b/c env context is broken https://github.com/actions/runner/issues/480
          # inputs: '{ "sam-hostname": "sam.${{ github.event.repository.name }}-${{ github.run_id }}.bee.envs-terra.bio", "ENV": "qa", "auth-service-account-email": "firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com" }'
          inputs: '{ "sam-hostname": "${{ inputs.sam-hostname }}", "ENV": "qa", "auth-service-account-email": "${{ inputs.auth-service-account-email }}" }'
